### ISSUE TITLE
how I can get the normal  texture with the ks,kd 

### ISSUE THREAD

**Issue by ghost** [postech-ami/paint-it#12]
When you import the mesh and the generated texture maps in Blender, you have to define the same shading pipeline as NVDiffrast (that we used to render & train our texture). 

You can refer to this https://github.com/postech-ami/Paint-it/issues/5#issuecomment-2039579293. Here, you can find the Blender Python script to import your mesh and texture, similar to the NVDiffrast.

Please let us know if you have more questions.
Thanks.

_Originally posted by @Youwang-Kim in https://github.com/postech-ami/Paint-it/issues/7#issuecomment-2048916325_

**Comment by Youwang-Kim** [comment]
Hi, thanks for your interest in our work. 

Our code automatically saves the Kd, Ks, and Normal map in the log directory.
Please refer to the below code:
https://github.com/postech-ami/Paint-it/blob/407c55b4255dd8e13fd950313ea860cf0ffe71e2/paint_it.py#L252-L263

The `write_obj(output_dir, vis_mesh)` line will save all the texture maps that you need, including the normal map.

Please let us know if you have more questions.

Thanks.

**Comment by zhoushiwei** [comment]
> Hi, thanks for your interest in our work.
> 
> Our code automatically saves the Kd, Ks, and Normal map in the log directory. Please refer to the below code:
> 
> https://github.com/postech-ami/Paint-it/blob/407c55b4255dd8e13fd950313ea860cf0ffe71e2/paint_it.py#L252-L263
> 
> The `write_obj(output_dir, vis_mesh)` line will save all the texture maps that you need, including the normal map.
> 
> Please let us know if you have more questions.
> 
> Thanks.
<img width="396" alt="截屏2024-04-15 17 39 26" src="https://github.com/postech-ami/Paint-it/assets/10701821/6c0999ac-3eb0-4329-b781-2ea6d40a5df0">
![final_front](https://github.com/postech-ami/Paint-it/assets/10701821/51af0235-e599-42bf-9eca-53613049017c)


I know ,but the result is vert differene with the final image

**Comment by AIGCAI** [comment]
but the save result is not as the same as the fina_image

**Comment by Youwang-Kim** [comment]
Please note that the saved texture maps are in UV coordinates. 
So, the texture map images themselves should look different from the images of the meshes.

**Comment by AIGCAI** [comment]
Thanks for the reply, what I mean is that the combination of the saved kd,ks,normal which is rendered by the rendering is not quite the same as the result rendered by your algorithm

**Comment by Youwang-Kim** [comment]
Which rendering engine did you use?
During generation, we use NVIDIA's differentiable rasterizer and its shader. So if you're using another renderer or shader, you must build the same rendering pipeline as our shading pipeline. 

For example, if you're using Blender, you can refer to the scripts mentioned here:
https://github.com/postech-ami/Paint-it/issues/5#issuecomment-2039579293

But still, please note that the rendering pipelines for NVDiffrast and Blender are different, so they may not look identical.

**Comment by AIGCAI** [comment]
ok ,Maybe it's the rendering engine, by the way, when will you  support SDXL? Is it possible in the future to support inputs that are images instead of text?

**Comment by AIGCAI** [comment]
![final_top](https://github.com/postech-ami/Paint-it/assets/166797676/a79d5c24-8028-430d-8e61-561f5fbe0ed5)
Hi, why is it that the picture I ran of this pretzel is not the same as the one in your paper

**Comment by Youwang-Kim** [comment]
Hi, did you run the code with the default parameters that we suggested? 
I just run the code with the default setting, and I got result as below:
![iTerm2 rCU0TE final_top](https://github.com/postech-ami/Paint-it/assets/55628873/1d1cb9fb-9e3b-47e1-a591-26ab10858fd3)

Also, since our method uses Score-Distillation Sampling (SDS), which involves the random sampling of the diffusion time steps, your result may vary from the one in our paper. However, it shouldn't be as different as you showed. 

Please check your argument or other settings.

**Comment by zhoushiwei** [comment]
I just re-downloaded the source code and ran it again, and found that the result is still the same, and I realized that the sds loss on my side has never changed.
![Uploading 截屏2024-04-16 16.58.51.png…]()

**Comment by AIGCAI** [comment]
I just re-downloaded the source code and ran it again, and found that the result is still the same, and I realized that the sds loss on my side has never changed.
![Uploading 截屏2024-04-16 16.58.51.png…]()

**Comment by AIGCAI** [comment]
I just re-downloaded the source code and ran it again, and found that the result is still the same, and I realized that the sds loss on my side has never changed.
<img width="953" alt="截屏2024-04-16 16 58 51" src="https://github.com/postech-ami/Paint-it/assets/166797676/2a3aa06c-1d40-4626-abab-ad1a79b6542c">

**Comment by Youwang-Kim** [comment]
Getting 1.000 for SDS loss is normal behavior.

If you look at the code implementation of SDS, it computes the custom gradient since, according to the original DreamFusion paper, we need to omit the diffusion U-Net Jacobian. The forward pass just outputs the dummy value of 1.0. Note that SDS computes the backward gradient, not the exact loss value. Please refer to the below code:

https://github.com/postech-ami/Paint-it/blob/407c55b4255dd8e13fd950313ea860cf0ffe71e2/sd.py#L16-L22

Regarding the visual quality, it is weird since we consistently obtain better results than the one you showed. 
Which GPU are you using? Are you using 4 rendered views per iteration?
Could you please try with different random seeds?

**Comment by AIGCAI** [comment]
L40s machine, all other configurations are default, what GPUs are you using on your

**Comment by Youwang-Kim** [comment]
We have tested on NVIDIA RTX A6000 and A100 machines, and got good results for the pretzel example. 
Could you please try with other machines?

**Comment by AIGCAI** [comment]
Ok,Iwill try . I think it may have something to do with the random seed, your default code does not seem to set the random seed, I should be under the random seed, the results will come out a little better, but still a little strange, the following two graphs are iterative 500 and 1500 effect graphs
![obj_0500](https://github.com/postech-ami/Paint-it/assets/166797676/e79b7aad-372d-4e1b-b1e5-c2fbd281e3f2)
![obj_1500](https://github.com/postech-ami/Paint-it/assets/166797676/cde4bed7-7d5a-475a-8cea-978064e8f04f)

**Comment by ghost** [comment]
Hi, if I first blend in the Zero123++ image to multi-view solution to go replace the current text to image,  Is it feasible?What should I change?

**Comment by AIGCAI** [comment]
> Hi, did you run the code with the default parameters that we suggested? I just run the code with the default setting, and I got result as below: ![iTerm2 rCU0TE final_top](https://private-user-images.githubusercontent.com/55628873/322766229-1d1cb9fb-9e3b-47e1-a591-26ab10858fd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzUxOTUsIm5iZiI6MTcxMzg3NDg5NSwicGF0aCI6Ii81NTYyODg3My8zMjI3NjYyMjktMWQxY2I5ZmItOWUzYi00N2UxLWE1OTEtMjZhYjEwODU4ZmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyMjEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZTY4ODJkYzgwYzNmMTVmZWYyODBhZGYyZWZkZjQ1Y2EwYzZkMDNkMWI5ZDkwNDEyZDU3OGM2ZWQ5OTI0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bWN8MWwjChC7WSBJU7HvKPvJqDMTj07Hp2b-toypI2w)
> 
> Also, since our method uses Score-Distillation Sampling (SDS), which involves the random sampling of the diffusion time steps, your result may vary from the one in our paper. However, it shouldn't be as different as you showed.
> 
> Please check your argument or other settings.

with all the same settings in A100，
![final_top (1)](https://github.com/postech-ami/Paint-it/assets/166797676/c6f9090c-dc06-4e67-8f4e-36629d27ab6d)
I think Is it possible that you didn't submit some changes?

**Comment by Youwang-Kim** [comment]
Hi, we just newly downloaded the code and have run the code with the default settings.
And the result seems good, as we got before.

![iTerm2 U4GoY2 final_top](https://github.com/postech-ami/Paint-it/assets/55628873/cd9f6811-7c8a-4a69-a645-c61b541df8d0)


Could you please check if you have installed the libraries with the correct versions? 
Please check if you have the same versions of the libraries or CUDA as below:

```
conda create -n paint_it python=3.8
conda activate paint_it

# pytorch installation
pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113

# for pytorch3d installation
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
# for python3.8, cuda 11.3, pytorch 1.12 (py38_cu113_pyt1120) -> need to install pytorch3d-0.7.2 
pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu113_pyt1120/download.html

pip install git+https://github.com/NVlabs/nvdiffrast/
pip install diffusers==0.12.1 huggingface-hub==0.11.1 transformers==4.21.1 sentence-transformers==2.2.2
pip install PyOpenGL PyOpenGL_accelerate accelerate rich ninja scipy trimesh imageio matplotlib chumpy opencv-python
pip install numpy==1.23.1
```

**Comment by AIGCAI** [comment]
sorry , I found the problem ,It's because of SD's configuration parameters, I used my own local SD 2.1 version
