### ISSUE TITLE
how to get the depth image

### ISSUE THREAD

**Issue by ghost** [postech-ami/paint-it#14]

**Comment by Youwang-Kim** [comment]
Hi, 
For rendering the depth image, you may refer to the below links (from NVDiffRast repository)

1. https://github.com/NVlabs/nvdiffrast/issues/172
2. https://github.com/NVlabs/nvdiffrast/issues/118#issuecomment-1666875029

Thanks.

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.
