### ISSUE TITLE
Texture Generation for Building Models Appears Overly Simple and Unrealistic

### ISSUE THREAD

**Issue by bdcms1** [postech-ami/paint-it#15]
When generating textures for architectural mesh models with the prompt Texts "residential building, red bricks facade, wooden roof," the resulting textures appear too simplistic and lack realism. The walls do not convey the appearance of red bricks, and the roof fails to resemble a wooden roof as intended.
Thank you very much and looking forward to your response.

**Comment by Youwang-Kim** [comment]
Hi, 
We recommend you methods like increasing the number of renderings and adjusting the range of sampling camera viewpoint.

Thanks for your interest.

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.
