### ISSUE TITLE
About improving texture resolution

### ISSUE THREAD

**Issue by THU-Yu-Shang** [postech-ami/paint-it#17]
Hi, which parameter should I change if I want to increase the resolution of the generated texture?
Or is there any other way to improve the resolution and quality of the final textured 3D models?
Thanks!

**Comment by Youwang-Kim** [comment]
Hi, 
Thanks for your interest in our work.

We've added `uv_res` as an argument parameter when running our code. The default value is set to 512, but you can adjust it to 1024 or other resolutions. It will work in arbitrary resolutions, but you may need to adjust some U-Net layer configurations if the results are not good. Also, you'll need more computational resource (GPU memory) to run our code in higher resolution.

Here is the argument option for `uv_res`:
https://github.com/postech-ami/Paint-it/blob/d7494e6660f2964aa03956d81505b07787260ccb/paint_it.py#L59


and this will affect two parts of our code:
https://github.com/postech-ami/Paint-it/blob/d7494e6660f2964aa03956d81505b07787260ccb/paint_it.py#L144
and
https://github.com/postech-ami/Paint-it/blob/d7494e6660f2964aa03956d81505b07787260ccb/paint_it.py#L166

Hope this answers your question.

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.
