### ISSUE TITLE
Why can't I get the same results as in the paper?

### ISSUE THREAD

**Issue by Rody-NKCS** [postech-ami/paint-it#18]
This is what I get when I run your code, and the prompt is "a basketball". I haven't modified any parameters, can you give me some advice on where I went wrong?
![image](https://github.com/postech-ami/Paint-it/assets/139108276/3e9a6e07-142f-4ddc-b7ac-4c719e60cd47)

**Comment by Rody1911641** [comment]
Thanks! I know what happens to me!

**Comment by zhoushiwei** [comment]
> Thanks! I know what happens to me!

maybe the sd model , check it

**Comment by Youwang-Kim** [comment]
Hi,

Glad that you've figured out the solutions. 
Please reopen this issue if you need more help regarding this.
