### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by muses0229** [postech-ami/paint-it#19]

**Comment by Youwang-Kim** [comment]
Hi, 
Thanks for your interest in our work.

There are two main ways to reduce the memory requirements.
But please note that these options may reduce the memory requirements **but will downgrade the output qualities.**

**1.  Decreasing the generated UV texture resolution**
We've added `uv_res` as an argument parameter when running our code. The default value is set to 512, but you can decrease the UV resolution values. It will work in arbitrary resolutions, but you may need to adjust some U-Net layer configurations if the results are not good. 
Here is the argument option for `uv_res`:
https://github.com/postech-ami/Paint-it/blob/d7494e6660f2964aa03956d81505b07787260ccb/paint_it.py#L59

**2. Decreasing the number of rendered views during optimization**
You can also decrease the number of object renderings. You can adjust it using this argument parameter:
https://github.com/postech-ami/Paint-it/blob/d7494e6660f2964aa03956d81505b07787260ccb/paint_it.py#L53

Hope this answers your question.

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.
