### ISSUE TITLE
Human Texture Generation Code ？

### ISSUE THREAD

**Issue by zcai0612** [postech-ami/paint-it#20]
Thanks a lot for your brilliant work.

Do you have any plans to release the code about human texture generation? What's the main difference in the current implementation?

**Comment by Youwang-Kim** [comment]
Hi, 
thanks for your interest in our work. 

We are planning to release the code for human texture generation before this September. 
The core differences would be camera view sampling strategies and mesh-related operations.

Stay tuned!

**Comment by Youwang-Kim** [comment]
Hi @zcai0612, the PBR generation code for 3D humans has been released just now :) 
You can refer to [this part](https://github.com/postech-ami/Paint-it?tab=readme-ov-file#generate-pbr-texture-maps-for-3d-human-mesh) as a starting point.
Try it out, and let us know if there are any problems!
