### ISSUE TITLE
The choise of UNet for reparameterization

### ISSUE THREAD

**Issue by 07hyx06** [postech-ami/paint-it#23]
Hi, thanks for your work!

Have you tried using a decoder-only architecture (e.g. StyleGAN generator) to reparameterize the UV maps? 
I have done some experiments to use different architectures to overfit a single image using L1 loss only (optimize all the network parameters to fit a single image). I find the UNet used in Paint-it can do it very well but the StyleGAN generator cannot perform well on this task. Do you have some insights on this experiment?

Thanks in advance.

**Comment by 07hyx06** [comment]
BTW I think reparameterization is a very neat idea and also recognize your work that applies parameterization technique to 3DMM fitting :)

**Comment by Youwang-Kim** [comment]
Hi, thanks for your interest in our work. 

I guess you're trying a task similar to the [Deep Image Prior (DIP)](https://dmitryulyanov.github.io/deep_image_prior) paper.
The authors of DIP have extensively compared the architecture choice, and we followed their conclusion (U-Net with skip connection). 

We have done experiments about removing the skip connection in our U-Net and observed that the skip connection is crucial for generating high-frequency details. But for other architectures (e.g., decoder-only), unfortunately we haven't done experiments. 

It'd be a really interesting direction to explore the optimal neural re-parameterization for various tasks :)

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.
