### ISSUE TITLE
There is no `sample_view_obj` function

### ISSUE THREAD

**Issue by Kitsunetic** [postech-ami/paint-it#3]
Hi, Thank you for sharing such a nice work!!

While running `paint_it.py` script, I found that there is no definition of function `sample_view_obj` in this repository.
Could you check and update please?

https://github.com/postech-ami/paint-it/blob/a1623f3b0e1bcd6c7103624c31c856485433545f/paint_it.py#L203

**Comment by Youwang-Kim** [comment]
Hi, thanks for your interest in our work, and reporting the missing function!!

The `sample_view_obj` function was indeed missing in the repository. Sorry for this.
I just updated the code, and you can find the function here:

https://github.com/postech-ami/paint-it/blob/c32b63c58ee9a0e43bf11530924e8e389feaac9e/utils.py#L17

Please let me know if you have remaining issues :) 

Thanks.
