### ISSUE TITLE
Default fp16 inference and potentially missing arguments

### ISSUE THREAD

**Issue by LIU-Yuxin** [postech-ami/paint-it#4]
Hi, thank you for releasing the code. I have a few issues encountered during testing.
One is that, could you please cast the model weight and input to fp16 by default so the model will work on consumer GPUs with around 20 GB memory? It will be more friendly for users without NV AI cards.
Another thing is that seems that some arguments are not set when running paint_it.py, such as objaverse_id (is it the same thing as obj_id), and the learn_lights argument. May I ask if you have tested your program by purely installing from the git repo, especially when some files are excluded from uploading.

**Comment by Youwang-Kim** [comment]
Hi, thanks for your interest in our work, and for reporting some issues in arguments.

We have modified and checked our codebase again (by installing from the git repo). It should work now.
Regarding fp16 model weight & input, we'll consider it as our to-do.

Please let me know if you have remaining issues :)
Thanks.

**Comment by LIU-Yuxin** [comment]
Thank you for fixing.
I will open separate issue if further issues exist.
