### ISSUE TITLE
Viewing in Blender?

### ISSUE THREAD

**Issue by jloveric** [postech-ami/paint-it#7]
Although the results look great with the nvdiff_renderer, not so much inside Blender. Greens appearing as florescent etc... I suspect this has to do with enabling the correct options inside blender or perhaps it isn't using one of the textures. Anybody else seen this and know how to fix it?

**Comment by jloveric** [comment]
I seem to be having the same issue in Rhino

**Comment by Youwang-Kim** [comment]
Hi, thanks for your interest in our work. 
When you import the mesh and the generated texture maps in Blender, you have to define the same shading pipeline as NVDiffrast (that we used to render & train our texture). 

You can refer to this https://github.com/postech-ami/Paint-it/issues/5#issuecomment-2039579293. Here, you can find the Blender Python script to import your mesh and texture, similar to the NVDiffrast.

Please let us know if you have more questions.
Thanks.

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.
