### ISSUE TITLE
Will there be any issues increasing the resolution of the texture

### ISSUE THREAD

**Issue by jloveric** [postech-ami/paint-it#8]
So far I haven't tried this for this technique, but so far the biggest issue I've run into with text to texture is not being able to generate fine enough textures (detailed 2048x2048 or larger for example).  I expect I'll run into memory issues, but is there any fundamental limitation? Do you see any issues with this using paint-it?

**Comment by Youwang-Kim** [comment]
Hi, thanks for your interest to our work. 

The DC-PBR representation uses U-Net as its architecture. Thus, if you increase the resulting texture map resolution, you would have to modify some architectural hyperparameters such as `num_channels_down`, `num_channels_up`, `num_channels_skip`, `filter_size_up`, `filter_size_down`. You can adjust those parameters here.
https://github.com/postech-ami/Paint-it/blob/407c55b4255dd8e13fd950313ea860cf0ffe71e2/paint_it.py#L81-L87

Please let us know if you have more questions.
Thanks.

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.
