### ISSUE TITLE
Code human meshes?

### ISSUE THREAD

**Issue by FaresMlk** [postech-ami/paint-it#9]
Hello,
Great work!

When is the expected release date for the code related to 3D human meshes?

Thanks.

**Comment by Youwang-Kim** [comment]
Hi, thanks for your interest in our work :) 
We are planning to release the code for 3D human meshes by the end of April.

Stay tuned!

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.

**Comment by Youwang-Kim** [comment]
Hi @FaresMlk, the PBR generation code for 3D humans has been released just now :)
You can refer to [this part](https://github.com/postech-ami/Paint-it?tab=readme-ov-file#generate-pbr-texture-maps-for-3d-human-mesh) as a starting point.
Try it out, and let us know if there are any problems!
